name: Docker Image 만들기

# Event : 실행되는 시점을 정의
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# 하나의 워크플로우에 여러 개의 job을 정의할 수 있음. 여기서는 My-Deploy-Job 하나만 정의
jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest  # 이 Job이 실행될 환경을 Ubuntu로 지정
    steps:
      - name: Checkout  # 코드 체크아웃 (GitHub 리포지토리의 소스 코드를 가져옴)
        uses: actions/checkout@v3  # GitHub의 공식 액션 사용
        with:
          submodules: recursive  # 서브모듈까지 포함해서 가져옴
          token: ${{secrets.PAT_TOKEN}}  # Private access token 사용

      - name: JDK 17 설치  # JDK 17을 설치하여 Java 환경 구성
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Java 17 사용
          distribution: 'temurin'  # Temurin 배포판 사용

      - name: Spring Project 빌드하기  # Spring 프로젝트를 빌드하는 단계
        run: |
          cd ./dev-route/
          chmod +x ./gradlew  # gradlew 파일에 실행 권한 부여
          ./gradlew clean build -x test  # 테스트를 제외하고 빌드 실행

      - name: Cache Docker layers  # Docker 레이어 캐싱을 통한 CPU 사용률 최적화
        uses: actions/cache@v2  # GitHub Actions의 캐시 액션 사용
        with:
          path: /tmp/.buildx-cache  # Docker 빌드 캐시를 저장할 경로
          key: ${{ runner.os }}-buildx-${{ github.sha }}  # 캐시 키 설정
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Docker 이미지 만들고 Dockerhub에 푸시  # Docker 이미지 빌드 및 DockerHub에 푸시
        run: |
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}  # DockerHub 로그인
          cd ./dev-route/  # dev-route 디렉터리로 이동
          docker build --cache-from type=local,src=/tmp/.buildx-cache -t ${{secrets.DOCKER_REPO}}/devroute-server:${{github.sha}} .  # 캐시 활용해 Docker 이미지 빌드
          docker push ${{secrets.DOCKER_REPO}}/devroute-server:${{github.sha}}  # DockerHub에 이미지 푸시

      - name: EC2에서 이미지 pull 후, 컨테이너 실행  # EC2 서버에서 Docker 이미지 pull 및 실행
        uses: appleboy/ssh-action@master  # EC2 서버에 SSH로 접속해 명령 실행
        with:
          host: ${{ secrets.EC2_HOST }}  # EC2 인스턴스의 호스트 정보
          username: ${{ secrets.EC2_SSH_USER }}  # SSH 접속할 사용자 이름
          key: ${{ secrets.PRIVATE_KEY }}  # SSH 프라이빗 키
          script: |  # EC2 서버에서 실행할 스크립트
            docker rm -f $(docker ps -qa)  # 실행 중인 모든 컨테이너 제거
            docker run -d -p 8080:8080 -e "SPRING_PROFILES_ACTIVE=prod" ${{secrets.DOCKER_REPO}}/devroute-server:${{github.sha}}  # 새 컨테이너 실행
