name: Docker Image 만들기

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{secrets.PAT_TOKEN}}

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Spring Project 빌드하기
        run: |
          cd ./dev-route/
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Docker 이미지 만들고 Dockerhub에 푸시
        run: |
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
          cd ./dev-route/
          docker build -t ${{secrets.DOCKER_REPO}}/devroute-server:${{github.sha}} .
          docker push ${{secrets.DOCKER_REPO}}/devroute-server:${{github.sha}}

      - name: EC2에서 이미지 pull 후, 컨테이너 실행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            # 8080 포트를 사용하는 컨테이너 중지 및 삭제
            docker ps --filter "publish=8080" -q | xargs -r docker stop
            docker ps -a --filter "publish=8080" -q | xargs -r docker rm
            
            # 새 이미지를 pull하고 실행
            docker pull ${{secrets.DOCKER_REPO}}/devroute-server:${{github.sha}}
            docker run -d -p 8080:8080 ${{secrets.DOCKER_REPO}}/devroute-server:${{github.sha}}
